#!/bin/bash
# Script to restart Odoo and upgrade the attendance_timeoff_automation module

echo "=========================================="
echo "Restarting Odoo and Upgrading Module"
echo "=========================================="

# Instructions for manual restart
echo ""
echo "STEP 1: Restart Odoo Server"
echo "----------------------------"
echo "If Odoo is running as a service:"
echo "  sudo systemctl restart odoo17"
echo "  # or"
echo "  sudo systemctl restart odoo"
echo ""
echo "If Odoo is running in terminal:"
echo "  Press Ctrl+C to stop it, then restart"
echo ""
echo "If using Docker:"
echo "  docker restart odoo"
echo ""

echo "STEP 2: Upgrade the Module"
echo "----------------------------"
echo "Option A - Using Odoo CLI:"
echo "  /odoo17/odoo17-server/odoo-bin -u attendance_timeoff_automation -d YOUR_DATABASE_NAME"
echo ""
echo "Option B - Using Odoo UI:"
echo "  1. Go to Apps menu"
echo "  2. Remove 'Apps' filter"
echo "  3. Search: 'Attendance And Time off Automation'"
echo "  4. Click 'Upgrade' button"
echo ""

echo "STEP 3: Configure Leave Types"
echo "----------------------------"
echo "After upgrading, add codes to your leave types:"
echo "  1. Go to: Time Off → Configuration → Time Off Types"
echo "  2. For each leave type, add the Code field:"
echo "     - Annual Leave → ANNUAL"
echo "     - Sick Leave → SICK"
echo "     - Public Holiday → HOLIDAY"
echo "     - Unpaid Leave → UNPAID"
echo ""

echo "STEP 4: Test the Cron Jobs"
echo "----------------------------"
echo "  1. Go to: Settings → Technical → Automation → Scheduled Actions"
echo "  2. Find 'Create Automated Attendances (Weekends & Time Off)'"
echo "  3. Click 'Run Manually'"
echo "  4. Find 'Auto Allocate Employee Leaves'"
echo "  5. Click 'Run Manually'"
echo ""
echo "=========================================="
